### ISSUE TITLE
CSS Snippet for a dark mode

### ISSUE THREAD

**Issue by melmaninga** [nguyenvanduocit/obsidian-open-gate#52]
I like your plugin.  Great work!

Is there a CSS snippet that will allow for dark mode for particular gates?

**Comment by melmaninga** [comment]
Cool! How do I implement darkreader.js?

**Comment by nguyenvanduocit** [comment]
You need custom JS for it, custom js is not implementd yet, haha

**Comment by nguyenvanduocit** [comment]
Please wait a minute, new version will be rolled out. In v1.11.0. You can custom JS. So that you can add darkreader by using this js:

```
const script = document.createElement('script');
script.src = 'https://cdn.jsdelivr.net/npm/darkreader@4.9/darkreader.min.js';
script.onload = () => {  
DarkReader.enable({
    brightness: 100,
    contrast: 90,
    sepia: 10
  });
};
document.head.appendChild(script);
```

The only problem is we need to load darkreader from internet, and the page will be white for a second befor the script is fully loaded.

I want to include the lib into the plugin, but it will make the plugin heavier, and it does not make sense. so, ... it's what we have.

**Comment by nguyenvanduocit** [comment]
@andrewmcgivery solution work very well
