### ISSUE TITLE
Remove data collection

### ISSUE THREAD

**Issue by joethei** [nguyenvanduocit/obsidian-open-gate#9]
Hi @nguyenvanduocit 
We (the Obsidian team) noticed that the OpenGate plugin has client-side telemetry code posting user data to Datadog from within Obsidian directly.
We are still drafting a privacy and data collection policy for plugins, but there are a few guidelines we have already agreed on.
Mainly, plugins should not submit user data to third-party telemetry services from directly within Obsidian, even if the data collection is opt-in.

Client-side libraries like Datadog's make it too easy for user data unrelated to your plugin to get collected.
We therefore ask you to remove the data collection from this plugin.

**Comment by nguyenvanduocit** [comment]
The plugin did not send data to Datadog, you can see in the Developer Tool > network tab .

I used to want to do it, because my user got some bug but I don't know what happened. I really need to monitor the plugin. I added the dependency, draft a version. But someone in your team said like you. Then I had removed the code and update new version (without datadog) right after that. 

But the dependency is still in the package.json. not in the built files.

I will remove the dependency.

Obsidian need to provide some API that allow developer to monitor their plugin. Something like Shopify's Pixel API. Give us some event bus to hook our callback function.

**Comment by joethei** [comment]
Oops, thanks for the clarification
